package com.tracy.dao.impl;

import com.tracy.dao.ICrudUserDao;
import com.tracy.model.User;
import com.tracy.model.UserExample;
import com.ximalaya.live.dao.BaseDao;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Repository;

@Repository
@SuppressWarnings("deprecation")
public class CrudUserDao extends BaseDao implements ICrudUserDao {
    private final Logger log = LoggerFactory.getLogger(getClass());

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public CrudUserDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int countByExample(UserExample example) {
        if(log.isDebugEnabled()) {
            log.debug("Count records from table tb_user with example {}", example);
        }
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("WeChat_tb_user.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int deleteByExample(UserExample example) {
        if(log.isDebugEnabled()) {
            log.debug("Delete records from table tb_user with example {}", example);
        }
        int rows = getSqlMapClientTemplate().delete("WeChat_tb_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int deleteByPrimaryKey(Long id) {
        User _key = new User();
        _key.setId(id);
        if(log.isDebugEnabled()) {
            log.debug("Delete record {} from table tb_user.", _key);
        }
        int rows = getSqlMapClientTemplate().delete("WeChat_tb_user.ibatorgenerated_deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void insert(User record) {
        if(log.isDebugEnabled()) {
            log.debug("Insert record {} into table tb_user.", record);
        }
        getSqlMapClientTemplate().insert("WeChat_tb_user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void insertSelective(User record) {
        if(log.isDebugEnabled()) {
            log.debug("Insert record {} into table tb_user.", record);
        }
        getSqlMapClientTemplate().insert("WeChat_tb_user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<User> selectByExample(UserExample example) {
        if(log.isDebugEnabled()) {
            log.debug("Query records from table tb_user with example {}", example);
        }
        List<User> list = getSqlMapClientTemplate().queryForList("WeChat_tb_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public User selectByPrimaryKey(Long id) {
        if(log.isDebugEnabled()) {
            log.debug("Query record from table tb_user by id {}", id);
        }
        User _key = new User();
        _key.setId(id);
        User record = (User) getSqlMapClientTemplate().queryForObject("WeChat_tb_user.ibatorgenerated_selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int updateByExampleSelective(User record, UserExample example) {
        if(log.isDebugEnabled()) {
            log.debug("Update record into {} in table tb_user with example {}", record, example);
        }
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("WeChat_tb_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int updateByExample(User record, UserExample example) {
        if(log.isDebugEnabled()) {
            log.debug("Update record into {} in table tb_user with example {}", record, example);
        }
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("WeChat_tb_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int updateByPrimaryKeySelective(User record) {
        if(log.isDebugEnabled()) {
            log.debug("Update record {} in table tb_user.", record);
        }
        int rows = getSqlMapClientTemplate().update("WeChat_tb_user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int updateByPrimaryKey(User record) {
        if(log.isDebugEnabled()) {
            log.debug("Update record {} in table tb_user.", record);
        }
        int rows = getSqlMapClientTemplate().update("WeChat_tb_user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    protected static class UpdateByExampleParms extends UserExample {
        private Object record;

        public UpdateByExampleParms(Object record, UserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}