package com.tracy.dao.impl;

import com.tracy.dao.ICrudRecommendDao;
import com.tracy.model.Recommend;
import com.tracy.model.RecommendExample;
import com.ximalaya.live.dao.BaseDao;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Repository;

@Repository
@SuppressWarnings("deprecation")
public class CrudRecommendDao extends BaseDao implements ICrudRecommendDao {
    private final Logger log = LoggerFactory.getLogger(getClass());

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public CrudRecommendDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int countByExample(RecommendExample example) {
        if(log.isDebugEnabled()) {
            log.debug("Count records from table tb_recommend with example {}", example);
        }
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("WeChat_tb_recommend.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int deleteByExample(RecommendExample example) {
        if(log.isDebugEnabled()) {
            log.debug("Delete records from table tb_recommend with example {}", example);
        }
        int rows = getSqlMapClientTemplate().delete("WeChat_tb_recommend.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int deleteByPrimaryKey(Long id) {
        Recommend _key = new Recommend();
        _key.setId(id);
        if(log.isDebugEnabled()) {
            log.debug("Delete record {} from table tb_recommend.", _key);
        }
        int rows = getSqlMapClientTemplate().delete("WeChat_tb_recommend.ibatorgenerated_deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void insert(Recommend record) {
        if(log.isDebugEnabled()) {
            log.debug("Insert record {} into table tb_recommend.", record);
        }
        getSqlMapClientTemplate().insert("WeChat_tb_recommend.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void insertSelective(Recommend record) {
        if(log.isDebugEnabled()) {
            log.debug("Insert record {} into table tb_recommend.", record);
        }
        getSqlMapClientTemplate().insert("WeChat_tb_recommend.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<Recommend> selectByExample(RecommendExample example) {
        if(log.isDebugEnabled()) {
            log.debug("Query records from table tb_recommend with example {}", example);
        }
        List<Recommend> list = getSqlMapClientTemplate().queryForList("WeChat_tb_recommend.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public Recommend selectByPrimaryKey(Long id) {
        if(log.isDebugEnabled()) {
            log.debug("Query record from table tb_recommend by id {}", id);
        }
        Recommend _key = new Recommend();
        _key.setId(id);
        Recommend record = (Recommend) getSqlMapClientTemplate().queryForObject("WeChat_tb_recommend.ibatorgenerated_selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int updateByExampleSelective(Recommend record, RecommendExample example) {
        if(log.isDebugEnabled()) {
            log.debug("Update record into {} in table tb_recommend with example {}", record, example);
        }
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("WeChat_tb_recommend.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int updateByExample(Recommend record, RecommendExample example) {
        if(log.isDebugEnabled()) {
            log.debug("Update record into {} in table tb_recommend with example {}", record, example);
        }
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("WeChat_tb_recommend.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int updateByPrimaryKeySelective(Recommend record) {
        if(log.isDebugEnabled()) {
            log.debug("Update record {} in table tb_recommend.", record);
        }
        int rows = getSqlMapClientTemplate().update("WeChat_tb_recommend.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public int updateByPrimaryKey(Recommend record) {
        if(log.isDebugEnabled()) {
            log.debug("Update record {} in table tb_recommend.", record);
        }
        int rows = getSqlMapClientTemplate().update("WeChat_tb_recommend.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    protected static class UpdateByExampleParms extends RecommendExample {
        private Object record;

        public UpdateByExampleParms(Object record, RecommendExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}