package com.tracy.model;

import com.ximalaya.live.model.BaseModel;
import java.io.Serializable;

public class Recommend extends BaseModel implements Serializable {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_recommend.id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_recommend.from_id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private Integer fromId;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_recommend.time
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private Long time;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_recommend.from_open_id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String fromOpenId;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_recommend.to_open_id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String toOpenId;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_recommend.id
     *
     * @return the value of tb_recommend.id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_recommend.id
     *
     * @param id the value for tb_recommend.id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_recommend.from_id
     *
     * @return the value of tb_recommend.from_id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_recommend.from_id
     *
     * @param fromId the value for tb_recommend.from_id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_recommend.time
     *
     * @return the value of tb_recommend.time
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_recommend.time
     *
     * @param time the value for tb_recommend.time
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_recommend.from_open_id
     *
     * @return the value of tb_recommend.from_open_id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getFromOpenId() {
        return fromOpenId;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_recommend.from_open_id
     *
     * @param fromOpenId the value for tb_recommend.from_open_id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setFromOpenId(String fromOpenId) {
        if (fromOpenId != null && fromOpenId.length() > 100) {
            throw new IllegalArgumentException("column from_open_id's length must less than 100");
        }
        this.fromOpenId = fromOpenId == null ? null : fromOpenId.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_recommend.to_open_id
     *
     * @return the value of tb_recommend.to_open_id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getToOpenId() {
        return toOpenId;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_recommend.to_open_id
     *
     * @param toOpenId the value for tb_recommend.to_open_id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setToOpenId(String toOpenId) {
        if (toOpenId != null && toOpenId.length() > 100) {
            throw new IllegalArgumentException("column to_open_id's length must less than 100");
        }
        this.toOpenId = toOpenId == null ? null : toOpenId.trim();
    }
}