package com.tracy.model;

import com.ximalaya.live.model.BaseModel;
import java.io.Serializable;

public class User extends BaseModel implements Serializable {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.openid
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String openid;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.subscribe
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private Integer subscribe;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.nickname
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.sex
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String sex;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.city
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String city;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.country
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String country;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.province
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String province;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.language
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String language;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.headimgurl
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String headimgurl;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.subscribe_time
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private Long subscribeTime;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.unionid
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String unionid;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.remark
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column tb_user.groupid
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private String groupid;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database table tb_user
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.openid
     *
     * @return the value of tb_user.openid
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.openid
     *
     * @param openid the value for tb_user.openid
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setOpenid(String openid) {
        if (openid != null && openid.length() > 100) {
            throw new IllegalArgumentException("column openid's length must less than 100");
        }
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.subscribe
     *
     * @return the value of tb_user.subscribe
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public Integer getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.subscribe
     *
     * @param subscribe the value for tb_user.subscribe
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.nickname
     *
     * @return the value of tb_user.nickname
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.nickname
     *
     * @param nickname the value for tb_user.nickname
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setNickname(String nickname) {
        if (nickname != null && nickname.length() > 20) {
            throw new IllegalArgumentException("column nickname's length must less than 20");
        }
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.sex
     *
     * @return the value of tb_user.sex
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.sex
     *
     * @param sex the value for tb_user.sex
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setSex(String sex) {
        if (sex != null && sex.length() > 11) {
            throw new IllegalArgumentException("column sex's length must less than 11");
        }
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.city
     *
     * @return the value of tb_user.city
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.city
     *
     * @param city the value for tb_user.city
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setCity(String city) {
        if (city != null && city.length() > 11) {
            throw new IllegalArgumentException("column city's length must less than 11");
        }
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.country
     *
     * @return the value of tb_user.country
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.country
     *
     * @param country the value for tb_user.country
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setCountry(String country) {
        if (country != null && country.length() > 11) {
            throw new IllegalArgumentException("column country's length must less than 11");
        }
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.province
     *
     * @return the value of tb_user.province
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.province
     *
     * @param province the value for tb_user.province
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setProvince(String province) {
        if (province != null && province.length() > 11) {
            throw new IllegalArgumentException("column province's length must less than 11");
        }
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.language
     *
     * @return the value of tb_user.language
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.language
     *
     * @param language the value for tb_user.language
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setLanguage(String language) {
        if (language != null && language.length() > 11) {
            throw new IllegalArgumentException("column language's length must less than 11");
        }
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.headimgurl
     *
     * @return the value of tb_user.headimgurl
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.headimgurl
     *
     * @param headimgurl the value for tb_user.headimgurl
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setHeadimgurl(String headimgurl) {
        if (headimgurl != null && headimgurl.length() > 150) {
            throw new IllegalArgumentException("column headimgurl's length must less than 150");
        }
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.subscribe_time
     *
     * @return the value of tb_user.subscribe_time
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public Long getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.subscribe_time
     *
     * @param subscribeTime the value for tb_user.subscribe_time
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setSubscribeTime(Long subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.unionid
     *
     * @return the value of tb_user.unionid
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.unionid
     *
     * @param unionid the value for tb_user.unionid
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setUnionid(String unionid) {
        if (unionid != null && unionid.length() > 20) {
            throw new IllegalArgumentException("column unionid's length must less than 20");
        }
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.remark
     *
     * @return the value of tb_user.remark
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.remark
     *
     * @param remark the value for tb_user.remark
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setRemark(String remark) {
        if (remark != null && remark.length() > 50) {
            throw new IllegalArgumentException("column remark's length must less than 50");
        }
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column tb_user.groupid
     *
     * @return the value of tb_user.groupid
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column tb_user.groupid
     *
     * @param groupid the value for tb_user.groupid
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    public void setGroupid(String groupid) {
        if (groupid != null && groupid.length() > 20) {
            throw new IllegalArgumentException("column groupid's length must less than 20");
        }
        this.groupid = groupid == null ? null : groupid.trim();
    }
}