package com.tracy.dao;

import com.tracy.model.Recommend;
import com.tracy.model.RecommendExample;
import java.util.List;

public interface ICrudRecommendDao {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    int countByExample(RecommendExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    int deleteByExample(RecommendExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    void insert(Recommend record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    void insertSelective(Recommend record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    List<Recommend> selectByExample(RecommendExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    Recommend selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    int updateByExampleSelective(Recommend record, RecommendExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    int updateByExample(Recommend record, RecommendExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    int updateByPrimaryKeySelective(Recommend record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table tb_recommend
     *
     * @ibatorgenerated Sun Apr 03 21:33:32 CST 2016
     */
    int updateByPrimaryKey(Recommend record);
}